spring:
  application:
      name: "GitHubRepoKK"
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
my:
  app:
    github:
      token: ${GITHUB_ACCESS_TOKEN}
server:
  port: 8256