spring:
  application:
      name: "GitHubRepoKK"
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8256
